### ISSUE TITLE
iptables persistant rules for max. connections per ip

### ISSUE THREAD

**Issue by derDezi** [TobleMiner/shoreline#10]
Would be nice if you could add this information to the readme

Connection Limit per IP via iptables (Port 1234)

Add in /etc/iptables/iptables.rules
-A INPUT -p tcp -m tcp --dport 1234 --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 10 --connlimit-mask 32 --connlimit-saddr -j REJECT --reject-with icmp-port-unreachable

Add in /etc/iptables/iptables.rules
-A INPUT -p tcp -m tcp --dport 1234 --tcp-flags FIN,SYN,RST,ACK SYN -m connlimit --connlimit-above 10 --connlimit-mask 128 --connlimit-saddr -j REJECT --reject-with icmp6-port-unreachable

**Comment by TobleMiner** [comment]
Fixed in #16
