### ISSUE TITLE
Pixelflut protocol implementation differs from default

### ISSUE THREAD

**Issue by craig** [TobleMiner/shoreline#12]
Default was: https://cccgoe.de/wiki/Pixelflut, it states this format for "PX":
8-figure: (rrggbbaa)
6-figure: (rrggbb) 

This is used in https://github.com/defnull/pixelflut

However shoreline says:
PX <x> <y> <rrggbb|aarrggbb>

So either it's a documentation mistake somewhere, or the protocols differ.

**Comment by TobleMiner** [comment]
Oops, the documentation is wrong. Shoreline uses the default rrggbbaa syntax.
