### ISSUE TITLE
`PX x y` API difference

### ISSUE THREAD

**Issue by noerw** [TobleMiner/shoreline#18]
`PX x y` returns `RRGGBBAA` values.
Any other server i looked at so far returns `RRGGBB`.
This may confuse clients. I'm unsure if there's a benefit of returning transparent pixels

**Comment by TobleMiner** [comment]
Thanks, I had no idea! I don't think there is any benefit to returning transparency values either. Especially since the alpha belending feature will squash them into an fully opaque color anyways.

**Comment by TobleMiner** [comment]
FIxed in 32d735318d2c5e773ce5ee323bc6bcfd58a2f7d5
