### ISSUE TITLE
VNC Frontend stops unintentionally 

### ISSUE THREAD

**Issue by Poeschl** [TobleMiner/shoreline#4]
Hi there, I'm trying to put shoreline into a docker container and I managed to get it build and setup inside docker.

On the execution of `shoreline - f vnc` I get the following log and the server exits.
```
root@caca98cfbb5e:/opt# shoreline -f vnc
30/01/2019 22:48:33 Listening for VNC connections on TCP port 5900
30/01/2019 22:48:33 Listening for VNC connections on TCP6 port 5900
Shutting down frontend 'VNC server frontend'
```

Do you have a hint where to look at? 

I use following debian packages for compiling: `make g++ libvncserver-dev libnuma-dev libsdl2-dev libpthread-workqueue-dev`
And those as non-dev versions on the runtime environment.

**Comment by TobleMiner** [comment]
Hey,

the behaviour you are seeing results from libvncserver reporting that the VNC server is no longer running. The framebuffer update loop checks wether the VNC server is still running: https://github.com/TobleMiner/shoreline/blob/master/vnc.c#L82

I'm not entirely sure why that happens though. It was merely designed to ensure shoreline would exit if a problem with the VNC server occured so it could be restarted. Does shoreline exit cleanly when this error occurs? What happens when you replace above line by `return 0;`? Does the VNC server work as expected?

**Comment by Poeschl** [comment]
I quickly checked the return value and shoreline gives me the exit code `9`.
I will check the line replacement tomorrow.

Btw what meaning has the font parameter for the vnc frontend? Can it impact the libvncserver ?

**Comment by TobleMiner** [comment]
Yes. The frontend parameters can change some parameters passed to libvncserver. You can use them to set the port the VNC server listens on and the font it uses to print on screen text. I've added a section to the readme that briefly descibes how to use frontend options.

I'm not quite sure why you are getting return code 9 though. You should always get a proper error message when anything fails. I'll add one to the frontend_update code, too and take another look at my initialization code. Maybe I missed some weird edge case.

**Comment by TobleMiner** [comment]
Hm, there was indeed another case where there would not be any error output. I've updated shoreline accordingly. Please feel free to try again with current master.

**Comment by Poeschl** [comment]
Tested it with the new master and got a more verbose error:
`Failed to resolve listen address '::', 9 => Address family for hostname not supported`

Thats something I can handle with the `-b` parameter.

**Comment by Poeschl** [comment]
The server inside a container is now available on: https://github.com/Poeschl/docker-shoreline

**Comment by TobleMiner** [comment]
Nice! Thanks for the report
