### ISSUE TITLE
Missing PX <x> <y> command

### ISSUE THREAD

**Issue by Poeschl** [TobleMiner/shoreline#5]
During use I noticed that the `PX <x> <y>` from the official documentation is not handled correctly.

It should return the color at the position `<x> <y>`.

Is there an easy way to patch this? (I'm before beginner on `C`)

FYI @TobiasSchaffner

**Comment by TobleMiner** [comment]
Yes, I should indeed add that. I'll look into implementing it.

**Comment by TobleMiner** [comment]
I've implemented the get pixel command on branch https://github.com/TobleMiner/shoreline/tree/implement-get-pixel I'll run some performance numbers in the next days and see if it does impact performance.

**Comment by TobleMiner** [comment]
First tests suggest that performance penalty is minimal (< 1%). I've just testet this on my Notebook though and will have to test on proper hardware tomorrow.

**Comment by TobleMiner** [comment]
Didn't get around to do another round of testing today, but will do so on Sunday or Monday.

**Comment by TobleMiner** [comment]
Just got around to do some more extensive testing on my EPYC system. Measurements indicate there is no appreciable performance difference (< 1%). Merged into master.
