### ISSUE TITLE
FEATURE: OFFSET Command not supported

### ISSUE THREAD

**Issue by craig** [TobleMiner/shoreline#8]
Many pixelflut servers (and clients) support the OFFSET command: 'OFFSET {x} {y}\n', but shoreline currently does not. It would be nice if it was implemented. :)

**Comment by TobleMiner** [comment]
Yeah, I'll take a look. Should not be too bad.

**Comment by TobleMiner** [comment]
Should be done

**Comment by craig** [comment]
Nice, thank you! :+1:
